### PR TITLE
made bluebird an optional dependency 

### PR DESCRIPTION
**Pull request by dereke**
bluebird will only be used if there are no native promises

### CODE REVIEW

**Comment by dereke** [comment]
yo @refractalize you should really merge this - it makes call stacks sane again!

**Comment by refractalize** [comment]
I reckon just get rid of it altogether

**Comment by dereke** [comment]
yeah get rid of - you should use a polyfill if needed like https://www.npmjs.com/package/lie

**Comment by refractalize** [comment]
quicker just to remove it: 8a2b4494b9f5ab90dc18aacc17ee574f2395ad3c

in v1.2

**Pull request closed without merging**
